[package]
name = "temper-forge-forgejo-world"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
skein-lib.workspace = true
skein-json.workspace = true
temper-forge-forgejo.workspace = true
temper-world.workspace = true

[lints.rust]
unsafe_code = "deny"
unused_must_use = "deny"
