#!/usr/bin/env python3
"""Parse the operator's live Forgejo credential note into a shell env file.

The input file is intentionally free-form and private. This parser accepts the
current note shape without printing any secret values.
"""

from __future__ import annotations

import argparse
import os
import re
from pathlib import Path


def sh_quote(value: str) -> str:
    return "'" + value.replace("'", "'\\''") + "'"


def env_key(value: str) -> str:
    return re.sub(r"[^A-Za-z0-9]", "_", value).upper()


def parse(path: Path) -> tuple[dict[str, dict[str, str]], dict[str, str]]:
    roles: dict[str, dict[str, str]] = {}
    meta: dict[str, str] = {}
    current: str | None = None

    for raw in path.read_text(errors="replace").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        lower = line.lower()

        if lower.startswith("admin user") and ":" in line:
            meta["admin_user"] = line.split(":", 1)[1].strip()
            current = None
            continue
        if lower.startswith("pw") and ":" in line:
            meta["admin_password"] = line.split(":", 1)[1].strip()
            current = None
            continue
        if lower.startswith("gitnex api token") and ":" in line:
            meta["admin_token"] = line.split(":", 1)[1].strip()
            current = None
            continue
        if current and current.startswith("runner") and ":" not in line:
            # The private note stores the runner registration token on the
            # indented line following `runnerN:<password>`.
            meta["runner_token"] = line.strip()
            continue
        if lower.startswith("api token") and ":" in line:
            if current:
                roles.setdefault(current, {})["token"] = line.split(":", 1)[1].strip()
            continue

        # Role password lines are shaped like "engineer:<password>".
        if ":" in line:
            name, value = line.split(":", 1)
            key = name.strip().lower()
            if re.fullmatch(r"[a-z0-9_.-]+", key):
                roles.setdefault(key, {})["user"] = key
                roles[key]["password"] = value.strip()
                current = key
                continue

    return roles, meta


def complete_alias(roles: dict[str, dict[str, str]], alias: str, source: str) -> None:
    if alias in roles and roles[alias].get("token"):
        return
    if source in roles and roles[source].get("token"):
        copied = dict(roles[source])
        copied["user"] = roles[source].get("user", source)
        roles[alias] = copied


def complete_product_chat_human_alias(
    roles: dict[str, dict[str, str]],
    meta: dict[str, str],
    source: str,
) -> None:
    """Map product-chat human to a token for exactly the requested user.

    The private dogfood note often stores the operator's own API token in the
    admin metadata block rather than in a role-shaped `free:` section. Accept it
    only when the configured product-chat human is that same Forgejo login; never
    fall back to an admin/bot token for a different visible author.
    """
    requested = source.strip().lower()
    if not requested:
        return
    complete_alias(roles, "product-chat-human", requested)
    if roles.get("product-chat-human", {}).get("token"):
        return

    admin_user = meta.get("admin_user", "").strip()
    if requested != admin_user.lower() or not meta.get("admin_token"):
        return

    entry = {
        "user": admin_user,
        "token": meta["admin_token"],
    }
    if meta.get("admin_password"):
        entry["password"] = meta["admin_password"]
    roles["product-chat-human"] = entry


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", required=True)
    parser.add_argument("--out", required=True)
    parser.add_argument("--human-user", default="bot")
    parser.add_argument("--mechanical-user", default="bot")
    parser.add_argument("--product-manager-user", default="product-manager")
    parser.add_argument("--product-chat-human-user", default="")
    args = parser.parse_args()

    source = Path(os.path.expanduser(args.source))
    out = Path(args.out)
    if not source.exists():
        raise SystemExit(f"secrets source does not exist: {source}")

    roles, meta = parse(source)
    complete_alias(roles, "human", args.human_user.lower())
    complete_product_chat_human_alias(roles, meta, args.product_chat_human_user)
    complete_alias(roles, "product-manager", args.product_manager_user.lower())

    required = ["architect", "engineer", "reviewer", "owner"]
    missing = [role for role in required if not roles.get(role, {}).get("token")]
    if missing:
        raise SystemExit("missing token(s) for required role(s): " + ", ".join(missing))

    lines = ["# Generated by examples/dogfood/tools/parse_secrets.py; do not commit."]
    for key, value in sorted(meta.items()):
        lines.append(f"DOGFOOD_{env_key(key)}={sh_quote(value)}")

    identity_aliases = [
        "architect",
        "engineer",
        "reviewer",
        "owner",
        "human",
        "product-chat-human",
        "product-manager",
    ]
    for alias in identity_aliases:
        entry = roles.get(alias)
        if not entry or not entry.get("token"):
            continue
        key = env_key(alias)
        lines.append(f"TEMPER_FORGEJO_USER_{key}={sh_quote(entry.get('user', alias))}")
        lines.append(f"TEMPER_FORGEJO_TOKEN_{key}={sh_quote(entry['token'])}")
        if entry.get("password"):
            lines.append(f"TEMPER_FORGEJO_PASSWORD_{key}={sh_quote(entry['password'])}")

    runner = roles.get("runner1") or roles.get("runner")
    if runner:
        if runner.get("user"):
            lines.append(f"DOGFOOD_RUNNER_USER={sh_quote(runner['user'])}")
        if runner.get("password"):
            lines.append(f"DOGFOOD_RUNNER_PASSWORD={sh_quote(runner['password'])}")

    mechanical = roles.get(args.mechanical_user.lower()) or roles.get("bot") or roles.get("owner")
    if mechanical and mechanical.get("token"):
        lines.append(f"DOGFOOD_MECHANICAL_USER={sh_quote(mechanical.get('user', args.mechanical_user))}")
        lines.append(f"DOGFOOD_MECHANICAL_TOKEN={sh_quote(mechanical['token'])}")
        if mechanical.get("password"):
            lines.append(f"DOGFOOD_MECHANICAL_PASSWORD={sh_quote(mechanical['password'])}")

    permission_users = []
    for alias in identity_aliases:
        entry = roles.get(alias, {})
        user = entry.get("user") if entry.get("token") else None
        if user and user not in permission_users:
            permission_users.append(user)
    if mechanical and mechanical.get("user") and mechanical["user"] not in permission_users:
        permission_users.append(mechanical["user"])
    lines.append(f"DOGFOOD_PERMISSION_USERS={sh_quote(' '.join(permission_users))}")

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines) + "\n")
    os.chmod(out, 0o600)
    print(f"wrote {out} with {len(permission_users)} Forgejo user(s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
