name: ci
on: [push]
jobs:
  build:
    runs-on: host
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: validate repair
        run: |
          cargo fmt --check
          cargo test --quiet
