[package]
name = "temper-worker-protocol"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
skein-lib.workspace = true
skein-io.workspace = true
temper-channel.workspace = true
temper-worker-domain.workspace = true

[lints]
workspace = true
