//! Writing and reading the live-credentials secrets file (`--out`).

use std::path::Path;

use temper_workflow::RoleId;

use super::model::{ProvisionError, Provisioned, Result};

pub fn format_secrets_env(provisioned: &Provisioned) -> String {
    let mut out = String::new();
    out.push_str("# Generated by temper-provision-forgejo — live credentials, do not commit.\n");
    out.push_str(&format!(
        "TEMPER_FORGEJO_OWNER={}\n",
        sh_quote(&provisioned.owner)
    ));
    out.push_str(&format!(
        "TEMPER_FORGEJO_REPO={}\n",
        sh_quote(&provisioned.name)
    ));
    for (role, identity) in &provisioned.roles {
        let key = env_role_key(role.as_str());
        out.push_str(&format!(
            "TEMPER_FORGEJO_USER_{key}={}\n",
            sh_quote(&identity.user)
        ));
        out.push_str(&format!(
            "TEMPER_FORGEJO_TOKEN_{key}={}\n",
            sh_quote(&identity.token)
        ));
        out.push_str(&format!(
            "TEMPER_FORGEJO_PASSWORD_{key}={}\n",
            sh_quote(&identity.password)
        ));
    }
    // Automation (bot) identity for the mechanical worker. Emitted under a
    // dedicated prefix so launchers never mistake it for a role worker.
    out.push_str(&format!(
        "TEMPER_FORGEJO_BOT_USER={}\n",
        sh_quote(&provisioned.automation.user)
    ));
    out.push_str(&format!(
        "TEMPER_FORGEJO_BOT_TOKEN={}\n",
        sh_quote(&provisioned.automation.token)
    ));
    out.push_str(&format!(
        "TEMPER_FORGEJO_BOT_PASSWORD={}\n",
        sh_quote(&provisioned.automation.password)
    ));
    out
}

pub fn write_secrets_file(path: &Path, contents: &str) -> std::io::Result<()> {
    if let Some(parent) = path.parent()
        && !parent.as_os_str().is_empty()
    {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(path, contents)?;
    restrict_permissions(path)?;
    Ok(())
}

#[cfg(unix)]
fn restrict_permissions(path: &Path) -> std::io::Result<()> {
    use std::os::unix::fs::PermissionsExt;
    std::fs::set_permissions(path, std::fs::Permissions::from_mode(0o600))
}

#[cfg(not(unix))]
fn restrict_permissions(_path: &Path) -> std::io::Result<()> {
    Ok(())
}

/// Reads a provisioned role's minted token back out of a secrets file written
/// by [`write_secrets_file`]/[`format_secrets_env`].
///
/// This supports seed-only provisioning runs, where the entry issue is filed in
/// a second pass (after the workers are up) and the authoring role's token must
/// be recovered from the secrets file produced by the earlier provision pass.
pub fn role_token_from_secrets_file(path: &Path, role: &RoleId) -> Result<String> {
    let contents = std::fs::read_to_string(path)?;
    let key = env_role_key(role.as_str());
    let needle = format!("TEMPER_FORGEJO_TOKEN_{key}=");
    for line in contents.lines() {
        if let Some(rest) = line.strip_prefix(&needle) {
            return Ok(sh_unquote(rest.trim()));
        }
    }
    Err(ProvisionError::Shape {
        what: "intake seed author".into(),
        detail: format!(
            "no token for role `{role}` found in {} (expected TEMPER_FORGEJO_TOKEN_{key})",
            path.display()
        ),
    })
}

fn env_role_key(role: &str) -> String {
    role.chars()
        .map(|ch| {
            if ch.is_ascii_alphanumeric() {
                ch.to_ascii_uppercase()
            } else {
                '_'
            }
        })
        .collect()
}

fn sh_quote(value: &str) -> String {
    format!("'{}'", value.replace('\'', "'\\''"))
}

/// Reverses [`sh_quote`]: parses a POSIX single-quote-escaped shell word back to
/// its literal value. Tokens never contain quotes in practice, but this stays
/// faithful so it round-trips any value `sh_quote` can emit.
fn sh_unquote(value: &str) -> String {
    let mut out = String::new();
    let mut chars = value.chars().peekable();
    while let Some(ch) = chars.next() {
        match ch {
            '\'' => {
                while let Some(&next) = chars.peek() {
                    if next == '\'' {
                        chars.next();
                        break;
                    }
                    out.push(next);
                    chars.next();
                }
            }
            '\\' => {
                if let Some(&next) = chars.peek() {
                    out.push(next);
                    chars.next();
                }
            }
            other => out.push(other),
        }
    }
    out
}
