//! Jig runtime for the provider-neutral typed-lineage fixture.
//!
//! The fixture makes the model derive a terminal function selector from a
//! provider-shaped qualified symbol. Values are generated by the temporary MCP
//! server and are never copied into the checked-in Jig bundle or evidence.

use std::sync::atomic::{AtomicUsize, Ordering};
use std::sync::{Arc, Mutex};

use jig_core::{Reply, RequestView, Script, StopReason, Turn};
use jig_server::FakeLlm;
use serde_json::Value as JsonValue;

use super::{
    BOUNDED_GRAPH_RESULT_NEEDLE, MAX_MODEL_MESSAGE_BYTES, ModelObservations,
    RAW_PROVIDER_FAILURE_NEEDLE, SAFE_PROVIDER_FAILURE, is_current_root_source_result,
    messages_contain,
};

pub(super) fn start(
    request_count: Arc<AtomicUsize>,
    observations: Arc<Mutex<ModelObservations>>,
) -> Result<FakeLlm, String> {
    FakeLlm::start(Script::rule(move |view| {
        if !messages_contain(view, "ROLE: engineer") {
            return Reply::text("unexpected codebase-memory fake-LLM request");
        }
        request_count.fetch_add(1, Ordering::SeqCst);
        record_model_observations(view, &mut observations.lock().expect("observations lock"));
        reply(view)
    }))
    .map_err(|error| format!("start typed-lineage Jig fake LLM: {error}"))
}

fn record_model_observations(view: &RequestView, observations: &mut ModelObservations) {
    if messages_contain(view, "CODEBASE MEMORY") {
        observations.prompt_guidance_seen = true;
    }
    if messages_contain(view, "TYPED_LINEAGE_GRAPH_RESULT") {
        observations.memory_result_seen = true;
    }
    if messages_contain(view, "TYPED_LINEAGE_TRACE_RESULT") {
        observations.graph_trace_seen = true;
    }
    let current_root_source_results = view
        .messages
        .iter()
        .filter(|message| is_current_root_source_result(&message.content))
        .count();
    observations.current_root_source_seen |= current_root_source_results > 0;
    observations.current_root_source_results += current_root_source_results;
    if messages_contain(view, SAFE_PROVIDER_FAILURE) {
        observations.safe_failure_seen = true;
    }
    if messages_contain(view, RAW_PROVIDER_FAILURE_NEEDLE) {
        observations.raw_provider_text_seen = true;
    }
    if messages_contain(view, BOUNDED_GRAPH_RESULT_NEEDLE) {
        observations.bounded_graph_result_seen = true;
    }
    if view
        .messages
        .iter()
        .any(|message| message.content.len() > MAX_MODEL_MESSAGE_BYTES)
    {
        observations.oversized_message_seen = true;
    }
}

fn reply(view: &RequestView) -> Reply {
    match view.prior_tool_results {
        0 => tool_reply(
            "discover-typed-lineage-root",
            "codebase_memory_search_graph",
            serde_json::json!({"query": "implementation selection"}),
        ),
        1 => tool_reply(
            "trace-transformed-typed-descendant",
            "codebase_memory_trace_path",
            serde_json::json!({"function_name": transformed_terminal(view)}),
        ),
        2 => tool_reply(
            "read-current-root-implementation",
            "codebase_memory_get_code_snippet",
            serde_json::json!({"qualified_name": result_value(view, "qualified_name")}),
        ),
        3 => tool_reply(
            "read-current-root-focused-test",
            "codebase_memory_get_code_snippet",
            serde_json::json!({"qualified_name": result_value(view, "next")}),
        ),
        4 => {
            for fact in [
                "current_root",
                "caller_model",
                "implementation_source",
                "behavioral_test",
            ] {
                require_fact(
                    view,
                    fact,
                    "mutation requires complete current-root implementation, caller/model, and focused behavioral-test evidence",
                );
            }
            tool_reply(
                "write-minimal-repair-after-typed-lineage-evidence",
                "write",
                serde_json::json!({
                    "path": "demo/src/lib.rs",
                    "content": "pub fn choose_dispatch<'a>(value: &'a str, preferred: Option<&'a str>, _attempt: u32) -> &'a str {\n    preferred.unwrap_or(value)\n}\n"
                }),
            )
        }
        5 => tool_reply(
            "validate-minimal-typed-lineage-repair",
            "bash",
            serde_json::json!({"command": "cd demo && cargo fmt --check && cargo test --quiet", "timeout": 60}),
        ),
        6 => tool_reply(
            "submit-typed-lineage-repair",
            "submit_for_pr",
            serde_json::json!({"summary": "Consumed typed current-root lineage before the minimal repair."}),
        ),
        7 => Reply::text(
            r##"{"title":"Keep selected dispatch behavior","body":"# Implementation report\nConsumed provider-neutral typed current-root lineage before the minimal repair. `cargo fmt --check` and `cargo test --quiet` pass.","summary":"Consumed typed lineage before the minimal repair."}"##,
        ),
        turn => panic!("unexpected typed-lineage model turn {turn}"),
    }
}

fn tool_reply(id: &str, name: &str, args: JsonValue) -> Reply {
    Reply {
        turns: vec![Turn::ToolCall {
            id: id.to_string(),
            name: name.to_string(),
            args,
        }],
        usage: Default::default(),
        stop: StopReason::ToolCalls,
    }
}

fn transformed_terminal(view: &RequestView) -> String {
    let qualified = result_value(view, "qualifiedName");
    let Some((_, terminal)) = qualified.rsplit_once("::") else {
        panic!("provider result did not expose a transformable typed qualified symbol");
    };
    assert!(
        terminal != qualified,
        "later dependent selector must be a transformed typed representation"
    );
    terminal.to_string()
}

fn require_fact(view: &RequestView, fact: &str, reason: &str) {
    assert!(!result_values(view, fact).is_empty(), "{reason}");
}

fn result_value(view: &RequestView, field: &str) -> String {
    result_values(view, field)
        .pop()
        .expect("provider result omitted its transient typed selection")
}

fn result_values(view: &RequestView, field: &str) -> Vec<String> {
    view.messages
        .iter()
        .filter_map(|message| {
            if message.role != "tool" {
                return None;
            }
            provider_result(&message.content)?
                .get(field)
                .and_then(JsonValue::as_str)
                .map(str::to_string)
        })
        .collect()
}

fn provider_result(content: &str) -> Option<JsonValue> {
    let result = content
        .split_once("\n\n[Decision anchor:")
        .map_or(content, |(result, _)| result);
    serde_json::from_str(result).ok()
}

#[cfg(test)]
mod tests {
    use super::provider_result;

    #[test]
    fn removes_generic_anchor_guidance_before_parsing_a_provider_result() {
        let result = provider_result(
            r#"{"qualifiedName":"crate::fixture::selection"}

[Decision anchor: generic guidance]"#,
        )
        .expect("provider result before anchor parses");
        assert_eq!(result["qualifiedName"], "crate::fixture::selection");
    }
}
