//! Privacy-safe, per-run enforcement for codebase-memory decision anchors.
//!
//! The policy never retains provider text, model arguments, paths, source, or
//! target digests. The trusted wrapper resolves provider-shaped selections in
//! process and hands this state only a bounded typed lineage record.

use std::collections::{BTreeMap, BTreeSet};

use serde::{Deserialize, Serialize};
use temper_protocol_activity::{
    GraphCorrelationTargetKindV1, GraphCorrelationToolV1, GraphCorrelationV1,
};
use tongs::model::ToolCall;
use tongs::tools::{ToolEffects, ToolOutput};

use super::protocol::{CODEBASE_MEMORY_TOOL_PREFIX, SAFE_GRAPH_CORRELATION_DETAIL_KEY};

/// Reserved wrapper detail carrying a process-local-root-bound lineage record.
/// It is deliberately excluded from durable activity metadata.
pub const SAFE_DECISION_ANCHOR_LINEAGE_DETAIL_KEY: &str = "temper_decision_anchor_lineage_v1";
const DECISION_ANCHOR_LINEAGE_VERSION: u32 = 1;
/// Six is the complete closed set of targeted wrapper selector kinds.
pub const MAX_DECISION_ANCHOR_RESULT_TARGET_KINDS: usize = 6;

/// Fixed, model-visible explanation for a locally denied mutation.
pub const DECISION_ANCHOR_MUTATION_BLOCKED_MESSAGE: &str = "workspace mutation blocked until the successful decision anchor is consumed through later result-derived codebase-memory evidence for the implementation, caller/model, and focused behavioral tests";

/// Generic, privacy-safe correction injected after a successful result cannot
/// be consumed as the active anchor's typed descendant.
pub const DECISION_ANCHOR_RECOVERY_MESSAGE: &str = "decision-anchor recovery required: the successful graph result did not form a compatible current-root descendant. Do not mutate; make a later targeted recovery selection or stop without a product.";

/// Recovery is deliberately short: repeated unrelated or unconsumable results
/// must not spin the native agent into a mutation-free but landable-looking run.
const MAX_DECISION_ANCHOR_RECOVERY_ATTEMPTS: u8 = 2;

/// Closed selector kinds which may participate in a decision-anchor lineage.
/// Their wire names intentionally mirror the closed V1 graph-correlation
/// target types, but lineage is an in-process policy contract rather than an
/// activity-protocol extension.
#[derive(Clone, Copy, Debug, Eq, Ord, PartialEq, PartialOrd, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum DecisionAnchorTargetKindV1 {
    GraphQuery,
    Pattern,
    NamePattern,
    QualifiedNamePattern,
    FunctionName,
    QualifiedName,
}

impl DecisionAnchorTargetKindV1 {
    /// Maps the existing closed activity correlation kind without widening it.
    pub const fn from_graph_correlation(kind: GraphCorrelationTargetKindV1) -> Self {
        match kind {
            GraphCorrelationTargetKindV1::GraphQuery => Self::GraphQuery,
            GraphCorrelationTargetKindV1::Pattern => Self::Pattern,
            GraphCorrelationTargetKindV1::NamePattern => Self::NamePattern,
            GraphCorrelationTargetKindV1::QualifiedNamePattern => Self::QualifiedNamePattern,
            GraphCorrelationTargetKindV1::FunctionName => Self::FunctionName,
            GraphCorrelationTargetKindV1::QualifiedName => Self::QualifiedName,
        }
    }

    const fn is_result_target_kind(self) -> bool {
        matches!(
            self,
            Self::Pattern | Self::FunctionName | Self::QualifiedName
        )
    }

    /// Returns whether a provider-result representation may be carried into a
    /// later wrapper selector. Only exact qualified symbols and their terminal
    /// function representation are intentionally equivalent.
    pub const fn can_carry_forward(self, next: Self) -> bool {
        matches!(
            (self, next),
            (
                Self::QualifiedName,
                Self::QualifiedName | Self::FunctionName | Self::Pattern
            ) | (Self::FunctionName, Self::FunctionName | Self::Pattern)
        )
    }
}

/// Whether this record begins a new root or was matched to an earlier complete
/// provider result by the trusted wrapper.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum DecisionAnchorLineageStageV1 {
    Root,
    CarryForward,
}

/// Versioned, bounded, provider-neutral decision-anchor lineage.
///
/// `root_binding` is an opaque v4 UUID generated by the wrapper. It binds
/// every carry-forward record to one current root but contains no provider,
/// model, path, source, target, or digest. `result_target_kinds` exposes only
/// canonical aggregate type facts; exact candidate values remain wrapper-local.
#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct DecisionAnchorLineageV1 {
    pub version: u32,
    pub root_binding: String,
    pub stage: DecisionAnchorLineageStageV1,
    pub target_kind: DecisionAnchorTargetKindV1,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub result_target_kinds: Vec<DecisionAnchorTargetKindV1>,
}

impl DecisionAnchorLineageV1 {
    /// Builds the canonical form emitted by the trusted wrapper.
    pub fn new(
        root_binding: String,
        stage: DecisionAnchorLineageStageV1,
        target_kind: DecisionAnchorTargetKindV1,
        result_target_kinds: impl IntoIterator<Item = DecisionAnchorTargetKindV1>,
    ) -> Option<Self> {
        let mut result_target_kinds = result_target_kinds.into_iter().collect::<Vec<_>>();
        result_target_kinds.sort();
        result_target_kinds.dedup();
        (valid_root_binding(&root_binding)
            && result_target_kinds.len() <= MAX_DECISION_ANCHOR_RESULT_TARGET_KINDS
            && result_target_kinds
                .iter()
                .all(|kind| kind.is_result_target_kind()))
        .then_some(Self {
            version: DECISION_ANCHOR_LINEAGE_VERSION,
            root_binding,
            stage,
            target_kind,
            result_target_kinds,
        })
    }

    /// Rejects unknown versions, malformed opaque bindings, duplicate or
    /// non-canonical type lists, and records that do not match V1 correlation.
    pub fn is_valid(&self) -> bool {
        self.version == DECISION_ANCHOR_LINEAGE_VERSION
            && valid_root_binding(&self.root_binding)
            && self.result_target_kinds.len() <= MAX_DECISION_ANCHOR_RESULT_TARGET_KINDS
            && self
                .result_target_kinds
                .iter()
                .all(|kind| kind.is_result_target_kind())
            && self
                .result_target_kinds
                .windows(2)
                .all(|pair| pair[0] < pair[1])
    }

    /// Checks both the standalone contract and the existing closed V1 graph
    /// correlation carried beside it.
    pub fn is_valid_for(&self, correlation: &GraphCorrelationV1) -> bool {
        self.is_valid()
            && self.target_kind
                == DecisionAnchorTargetKindV1::from_graph_correlation(correlation.target_kind)
    }
}

fn valid_root_binding(value: &str) -> bool {
    value.len() == 36
        && value.as_bytes().get(14) == Some(&b'4')
        && matches!(value.as_bytes().get(19), Some(b'8' | b'9' | b'a' | b'b'))
        && value.bytes().enumerate().all(|(index, byte)| {
            matches!(index, 8 | 13 | 18 | 23) && byte == b'-'
                || !matches!(index, 8 | 13 | 18 | 23)
                    && byte.is_ascii_hexdigit()
                    && !byte.is_ascii_uppercase()
        })
}

pub(super) struct DecisionAnchorState {
    mutation_tools: BTreeSet<String>,
    phase: Option<AnchorPhase>,
    calls: BTreeMap<String, PendingCodebaseCall>,
}

enum AnchorPhase {
    Root(Anchor),
    Trail(Trail),
    Recovery(Recovery),
    Exhausted,
}

struct Anchor {
    produced_turn: usize,
    root_binding: String,
    result_target_kinds: BTreeSet<DecisionAnchorTargetKindV1>,
}

struct Trail {
    anchor: Anchor,
    evidence: SourceEvidence,
}

struct Recovery {
    anchor: Anchor,
    evidence: SourceEvidence,
    attempts: u8,
}

#[derive(Default)]
struct SourceEvidence {
    trace_turn: Option<usize>,
    source_reads_after_trace: u8,
}

struct PendingCodebaseCall {
    turn: usize,
}

struct AnchorOutput {
    lineage: DecisionAnchorLineageV1,
    tool: GraphCorrelationToolV1,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(super) enum DecisionAnchorTransition {
    Unchanged,
    RecoveryNeeded,
    RecoveryExhausted,
}

impl Anchor {
    fn from_output(turn: usize, lineage: &DecisionAnchorLineageV1) -> Self {
        Self {
            produced_turn: turn,
            root_binding: lineage.root_binding.clone(),
            result_target_kinds: lineage.result_target_kinds.iter().copied().collect(),
        }
    }

    fn is_consumable(&self) -> bool {
        !self.result_target_kinds.is_empty()
    }

    fn accepts(&self, call: &PendingCodebaseCall, lineage: &DecisionAnchorLineageV1) -> bool {
        call.turn > self.produced_turn
            && lineage.stage == DecisionAnchorLineageStageV1::CarryForward
            && lineage.root_binding == self.root_binding
            && self.result_target_kinds.contains(&lineage.target_kind)
    }
}

impl DecisionAnchorState {
    pub(super) fn from_effects(effects: &BTreeMap<String, ToolEffects>) -> Option<Self> {
        let mutation_tools = effects
            .iter()
            .filter(|(_, effect)| effect.writes)
            .map(|(name, _)| name.clone())
            .collect::<BTreeSet<_>>();
        let has_codebase_memory = effects
            .keys()
            .any(|name| name.starts_with(CODEBASE_MEMORY_TOOL_PREFIX));
        (has_codebase_memory && !mutation_tools.is_empty()).then_some(Self {
            mutation_tools,
            phase: None,
            calls: BTreeMap::new(),
        })
    }

    pub(super) fn on_tool_dispatched(&mut self, call: &ToolCall, turn: usize) {
        if !call.name.starts_with(CODEBASE_MEMORY_TOOL_PREFIX) {
            return;
        }
        if let Some(call_key) = GraphCorrelationV1::target_digest(&call.id) {
            self.calls.insert(call_key, PendingCodebaseCall { turn });
        }
    }

    pub(super) fn on_tool_finished(
        &mut self,
        id: &str,
        name: &str,
        output: &ToolOutput,
    ) -> DecisionAnchorTransition {
        let Some(call_key) = GraphCorrelationV1::target_digest(id) else {
            return DecisionAnchorTransition::Unchanged;
        };
        let Some(call) = self.calls.remove(&call_key) else {
            return DecisionAnchorTransition::Unchanged;
        };
        let Some(output) = anchor_output(name, output) else {
            return DecisionAnchorTransition::Unchanged;
        };
        let next_anchor = Anchor::from_output(call.turn, &output.lineage);

        match self.phase.take() {
            None if output.lineage.stage == DecisionAnchorLineageStageV1::Root => {
                self.install_root(next_anchor, 0)
            }
            Some(AnchorPhase::Root(root)) if call.turn <= root.produced_turn => {
                self.phase = Some(AnchorPhase::Root(root));
                DecisionAnchorTransition::Unchanged
            }
            Some(AnchorPhase::Root(root)) => self.advance_or_recover(
                root,
                SourceEvidence::default(),
                &call,
                &output,
                next_anchor,
                1,
            ),
            Some(AnchorPhase::Trail(trail)) if call.turn <= trail.anchor.produced_turn => {
                self.phase = Some(AnchorPhase::Trail(trail));
                DecisionAnchorTransition::Unchanged
            }
            Some(AnchorPhase::Trail(trail)) => self.advance_or_recover(
                trail.anchor,
                trail.evidence,
                &call,
                &output,
                next_anchor,
                1,
            ),
            Some(AnchorPhase::Recovery(recovery)) if call.turn <= recovery.anchor.produced_turn => {
                self.phase = Some(AnchorPhase::Recovery(recovery));
                DecisionAnchorTransition::Unchanged
            }
            Some(AnchorPhase::Recovery(recovery)) => {
                // Only an anchor that itself had no usable typed selections may
                // be replaced by a fresh later root. A cross-root result cannot
                // substitute for an otherwise consumable current root.
                if !recovery.anchor.is_consumable()
                    && call.turn > recovery.anchor.produced_turn
                    && output.lineage.stage == DecisionAnchorLineageStageV1::Root
                {
                    self.install_root(next_anchor, recovery.attempts.saturating_add(1))
                } else {
                    self.advance_or_recover(
                        recovery.anchor,
                        recovery.evidence,
                        &call,
                        &output,
                        next_anchor,
                        recovery.attempts.saturating_add(1),
                    )
                }
            }
            Some(AnchorPhase::Exhausted) => {
                self.phase = Some(AnchorPhase::Exhausted);
                DecisionAnchorTransition::Unchanged
            }
            None => {
                self.phase = None;
                DecisionAnchorTransition::Unchanged
            }
        }
    }

    fn install_root(&mut self, anchor: Anchor, attempts: u8) -> DecisionAnchorTransition {
        if anchor.is_consumable() {
            self.phase = Some(AnchorPhase::Root(anchor));
            DecisionAnchorTransition::Unchanged
        } else {
            self.enter_recovery(anchor, SourceEvidence::default(), attempts)
        }
    }

    fn advance_or_recover(
        &mut self,
        active: Anchor,
        mut evidence: SourceEvidence,
        call: &PendingCodebaseCall,
        output: &AnchorOutput,
        next_anchor: Anchor,
        recovery_attempts: u8,
    ) -> DecisionAnchorTransition {
        if active.accepts(call, &output.lineage) {
            evidence.record(output.tool, call.turn);
            if next_anchor.is_consumable() {
                self.phase = Some(AnchorPhase::Trail(Trail {
                    anchor: next_anchor,
                    evidence,
                }));
                DecisionAnchorTransition::Unchanged
            } else {
                self.enter_recovery(next_anchor, evidence, recovery_attempts)
            }
        } else {
            self.enter_recovery(active, evidence, recovery_attempts)
        }
    }

    fn enter_recovery(
        &mut self,
        anchor: Anchor,
        evidence: SourceEvidence,
        attempts: u8,
    ) -> DecisionAnchorTransition {
        if attempts >= MAX_DECISION_ANCHOR_RECOVERY_ATTEMPTS {
            self.phase = Some(AnchorPhase::Exhausted);
            DecisionAnchorTransition::RecoveryExhausted
        } else {
            self.phase = Some(AnchorPhase::Recovery(Recovery {
                anchor,
                evidence,
                attempts,
            }));
            DecisionAnchorTransition::RecoveryNeeded
        }
    }

    pub(super) fn blocks_mutation(&self, name: &str) -> bool {
        self.mutation_tools.contains(name)
            && self.phase.as_ref().is_some_and(|phase| match phase {
                AnchorPhase::Root(_) => true,
                AnchorPhase::Trail(trail) => !trail.evidence.is_complete(),
                AnchorPhase::Recovery(_) | AnchorPhase::Exhausted => true,
            })
    }
}

impl SourceEvidence {
    fn record(&mut self, tool: GraphCorrelationToolV1, turn: usize) {
        match tool {
            GraphCorrelationToolV1::TracePath => {
                self.trace_turn = Some(turn);
                self.source_reads_after_trace = 0;
            }
            GraphCorrelationToolV1::GetCodeSnippet
                if self.trace_turn.is_some_and(|trace_turn| turn > trace_turn) =>
            {
                self.source_reads_after_trace = self.source_reads_after_trace.saturating_add(1);
            }
            _ => {}
        }
    }

    fn is_complete(&self) -> bool {
        self.trace_turn.is_some() && self.source_reads_after_trace >= 2
    }
}

fn anchor_output(name: &str, output: &ToolOutput) -> Option<AnchorOutput> {
    if output.is_error || !name.starts_with(CODEBASE_MEMORY_TOOL_PREFIX) {
        return None;
    }
    let details = output.details.as_ref()?;
    let correlation: GraphCorrelationV1 =
        serde_json::from_value(details.get(SAFE_GRAPH_CORRELATION_DETAIL_KEY)?.clone()).ok()?;
    if !correlation.is_valid() || correlation.tool.public_name() != name {
        return None;
    }
    let lineage: DecisionAnchorLineageV1 = serde_json::from_value(
        details
            .get(SAFE_DECISION_ANCHOR_LINEAGE_DETAIL_KEY)?
            .clone(),
    )
    .ok()?;
    lineage.is_valid_for(&correlation).then_some(AnchorOutput {
        lineage,
        tool: correlation.tool,
    })
}
