//! Writing and reading the live-credentials secrets file (`--out`).
//!
//! This is the pre-`credentials.toml` output format used only by the demo
//! provision-forgejo CLI; `temper init` writes `credentials.toml` and never
//! touches this.

use std::path::Path;

use temper_workflow::RoleId;

use super::{ProvisionError, Provisioned, Result};

pub fn format_secrets_env(provisioned: &Provisioned) -> String {
    let mut out = String::new();
    out.push_str("# Generated by temper-provision-forgejo — live credentials, do not commit.\n");
    out.push_str(&format!(
        "TEMPER_FORGEJO_OWNER={}\n",
        sh_quote(&provisioned.owner)
    ));
    out.push_str(&format!(
        "TEMPER_FORGEJO_REPO={}\n",
        sh_quote(&provisioned.name)
    ));
    for (role, identity) in &provisioned.roles {
        let key = env_role_key(role.as_str());
        out.push_str(&format!(
            "TEMPER_FORGEJO_USER_{key}={}\n",
            sh_quote(&identity.user)
        ));
        out.push_str(&format!(
            "TEMPER_FORGEJO_TOKEN_{key}={}\n",
            sh_quote(&identity.token)
        ));
        out.push_str(&format!(
            "TEMPER_FORGEJO_PASSWORD_{key}={}\n",
            sh_quote(&identity.password)
        ));
    }
    // Automation (bot) identity for the mechanical worker. Emitted under a
    // dedicated prefix so launchers never mistake it for a role worker.
    out.push_str(&format!(
        "TEMPER_FORGEJO_BOT_USER={}\n",
        sh_quote(&provisioned.automation.user)
    ));
    out.push_str(&format!(
        "TEMPER_FORGEJO_BOT_TOKEN={}\n",
        sh_quote(&provisioned.automation.token)
    ));
    out.push_str(&format!(
        "TEMPER_FORGEJO_BOT_PASSWORD={}\n",
        sh_quote(&provisioned.automation.password)
    ));
    out
}

pub fn write_secrets_file(path: &Path, contents: &str) -> std::io::Result<()> {
    if let Some(parent) = path.parent()
        && !parent.as_os_str().is_empty()
    {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(path, contents)?;
    restrict_permissions(path)?;
    Ok(())
}

#[cfg(unix)]
fn restrict_permissions(path: &Path) -> std::io::Result<()> {
    use std::os::unix::fs::PermissionsExt;
    std::fs::set_permissions(path, std::fs::Permissions::from_mode(0o600))
}

#[cfg(not(unix))]
fn restrict_permissions(_path: &Path) -> std::io::Result<()> {
    Ok(())
}

/// Reads a provisioned role's minted token back out of a secrets file written
/// by [`write_secrets_file`]/[`format_secrets_env`].
///
/// This supports seed-only provisioning runs, where the entry issue is filed in
/// a second pass (after the workers are up) and the authoring role's token must
/// be recovered from the secrets file produced by the earlier provision pass.
pub fn role_token_from_secrets_file(path: &Path, role: &RoleId) -> Result<String> {
    let contents = std::fs::read_to_string(path)?;
    let key = env_role_key(role.as_str());
    let needle = format!("TEMPER_FORGEJO_TOKEN_{key}=");
    for line in contents.lines() {
        if let Some(rest) = line.strip_prefix(&needle) {
            return Ok(sh_unquote(rest.trim()));
        }
    }
    Err(ProvisionError::Shape {
        what: "intake seed author".into(),
        detail: format!(
            "no token for role `{role}` found in {} (expected TEMPER_FORGEJO_TOKEN_{key})",
            path.display()
        ),
    })
}

fn env_role_key(role: &str) -> String {
    role.chars()
        .map(|ch| {
            if ch.is_ascii_alphanumeric() {
                ch.to_ascii_uppercase()
            } else {
                '_'
            }
        })
        .collect()
}

fn sh_quote(value: &str) -> String {
    format!("'{}'", value.replace('\'', "'\\''"))
}

/// Reverses [`sh_quote`]: parses a POSIX single-quote-escaped shell word back to
/// its literal value. Tokens never contain quotes in practice, but this stays
/// faithful so it round-trips any value `sh_quote` can emit.
fn sh_unquote(value: &str) -> String {
    let mut out = String::new();
    let mut chars = value.chars().peekable();
    while let Some(ch) = chars.next() {
        match ch {
            '\'' => {
                while let Some(&next) = chars.peek() {
                    if next == '\'' {
                        chars.next();
                        break;
                    }
                    out.push(next);
                    chars.next();
                }
            }
            '\\' => {
                if let Some(&next) = chars.peek() {
                    out.push(next);
                    chars.next();
                }
            }
            other => out.push(other),
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use std::collections::BTreeMap;

    use temper_forge::RepositoryId;
    use temper_forge::config::FORGEJO_ROLE_PASSWORD as ROLE_PASSWORD;
    use temper_provision::{BOT_USER, Provisioned, RoleIdentity};
    use temper_workflow::RoleId;

    use super::*;

    #[test]
    fn role_token_round_trips_through_secrets_file() {
        let mut roles = BTreeMap::new();
        roles.insert(
            RoleId::new("code-reviewer"),
            RoleIdentity {
                user: "reviewer".into(),
                email: "reviewer@example.invalid".into(),
                token: "tok-with-'-quote".into(),
                password: ROLE_PASSWORD.into(),
            },
        );
        let env = format_secrets_env(&Provisioned {
            owner: "acme".into(),
            name: "service".into(),
            repository: RepositoryId::new("r"),
            roles,
            automation: RoleIdentity {
                user: BOT_USER.into(),
                email: "bot@example.invalid".into(),
                token: "bot-tok".into(),
                password: "bot-pw".into(),
            },
        });
        let dir = std::env::temp_dir().join(format!("temper-seed-token-{}", std::process::id()));
        std::fs::create_dir_all(&dir).expect("temp dir");
        let path = dir.join("roles.env");
        write_secrets_file(&path, &env).expect("write secrets file");

        let token = role_token_from_secrets_file(&path, &RoleId::new("code-reviewer"))
            .expect("recovers the role token");
        assert_eq!(token, "tok-with-'-quote");

        let missing = role_token_from_secrets_file(&path, &RoleId::new("architect"))
            .expect_err("absent role errors");
        assert!(matches!(missing, ProvisionError::Shape { .. }));

        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn secrets_env_escapes_single_quotes() {
        let mut roles = BTreeMap::new();
        roles.insert(
            RoleId::new("code-reviewer"),
            RoleIdentity {
                user: "reviewer".into(),
                email: "reviewer@example.invalid".into(),
                token: "tok".into(),
                password: "pw-with-'-quote".into(),
            },
        );
        let env = format_secrets_env(&Provisioned {
            owner: "acme".into(),
            name: "service".into(),
            repository: RepositoryId::new("r"),
            roles,
            automation: RoleIdentity {
                user: BOT_USER.into(),
                email: "bot@example.invalid".into(),
                token: "bot-tok".into(),
                password: "bot-pw".into(),
            },
        });
        assert!(env.contains("TEMPER_FORGEJO_TOKEN_CODE_REVIEWER='tok'"));
        assert!(env.contains(r"TEMPER_FORGEJO_PASSWORD_CODE_REVIEWER='pw-with-'\''-quote'"));
        assert!(env.contains("TEMPER_FORGEJO_BOT_USER='bot'"));
        assert!(env.contains("TEMPER_FORGEJO_BOT_TOKEN='bot-tok'"));
        assert!(env.contains("TEMPER_FORGEJO_BOT_PASSWORD='bot-pw'"));
    }
}
