//! Privacy-safe decision lineage for targeted graph results.
//!
//! The trusted wrapper keeps provider values and selector matching local. This
//! record exposes only an opaque root binding and closed type facts, allowing
//! later-turn consumption to be audited without retaining arguments, source,
//! or provider text.

use serde::{Deserialize, Serialize};

use super::{GraphCorrelationTargetKindV1, GraphCorrelationV1};

const DECISION_ANCHOR_LINEAGE_VERSION: u32 = 1;
/// Six is the complete closed set of targeted wrapper selector kinds.
pub const MAX_DECISION_ANCHOR_RESULT_TARGET_KINDS: usize = 6;
/// A qualified provider identity has at most three portable suffix forms.
pub const MAX_DECISION_ANCHOR_CANONICAL_TARGET_DIGESTS: usize = 3;

/// Closed selector kinds which may participate in a decision-anchor lineage.
///
/// Their wire names intentionally mirror the closed V1 graph-correlation
/// target types, but lineage is a provider-neutral policy contract rather
/// than a provider-result extension.
#[derive(Clone, Copy, Debug, Eq, Ord, PartialEq, PartialOrd, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum DecisionAnchorTargetKindV1 {
    GraphQuery,
    Pattern,
    NamePattern,
    QualifiedNamePattern,
    FunctionName,
    QualifiedName,
}

impl DecisionAnchorTargetKindV1 {
    /// Maps the existing closed activity correlation kind without widening it.
    pub const fn from_graph_correlation(kind: GraphCorrelationTargetKindV1) -> Self {
        match kind {
            GraphCorrelationTargetKindV1::GraphQuery => Self::GraphQuery,
            GraphCorrelationTargetKindV1::Pattern => Self::Pattern,
            GraphCorrelationTargetKindV1::NamePattern => Self::NamePattern,
            GraphCorrelationTargetKindV1::QualifiedNamePattern => Self::QualifiedNamePattern,
            GraphCorrelationTargetKindV1::FunctionName => Self::FunctionName,
            GraphCorrelationTargetKindV1::QualifiedName => Self::QualifiedName,
        }
    }

    const fn is_result_target_kind(self) -> bool {
        matches!(
            self,
            Self::Pattern | Self::FunctionName | Self::QualifiedName
        )
    }

    /// Returns whether a provider-result representation may be carried into a
    /// later wrapper selector. Approved short symbols can also feed a
    /// `qualified_name` source selector when the provider uses that selector
    /// for a short caller/model identity; the opaque current-root binding
    /// still prevents cross-root substitution.
    pub const fn can_carry_forward(self, next: Self) -> bool {
        matches!(
            (self, next),
            (
                Self::QualifiedName,
                Self::QualifiedName | Self::FunctionName | Self::Pattern
            ) | (
                Self::FunctionName,
                Self::QualifiedName | Self::FunctionName | Self::Pattern
            )
        )
    }
}

/// Whether this record begins a new root or was matched to an earlier complete
/// provider result by the trusted wrapper.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum DecisionAnchorLineageStageV1 {
    Root,
    CarryForward,
}

/// Versioned, bounded, provider-neutral decision-anchor lineage.
///
/// `root_binding` is an opaque v4 UUID generated by the trusted wrapper. It
/// binds every carry-forward record to one current root but contains no
/// provider, model, path, source, target, or digest. `result_target_kinds`
/// exposes only canonical aggregate type facts; exact candidate values remain
/// wrapper-local.
#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct DecisionAnchorLineageV1 {
    pub version: u32,
    pub root_binding: String,
    pub stage: DecisionAnchorLineageStageV1,
    pub target_kind: DecisionAnchorTargetKindV1,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub result_target_kinds: Vec<DecisionAnchorTargetKindV1>,
    /// Digests of portable suffixes from the uniquely matched provider symbol.
    /// These are present only for a carry-forward selection; the raw provider
    /// symbol and model selector remain wrapper-local.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub canonical_target_digests: Vec<String>,
}

impl DecisionAnchorLineageV1 {
    /// Builds the canonical form emitted by the trusted wrapper.
    pub fn new(
        root_binding: String,
        stage: DecisionAnchorLineageStageV1,
        target_kind: DecisionAnchorTargetKindV1,
        result_target_kinds: impl IntoIterator<Item = DecisionAnchorTargetKindV1>,
    ) -> Option<Self> {
        Self::new_with_canonical_target_digests(
            root_binding,
            stage,
            target_kind,
            result_target_kinds,
            [],
        )
    }

    /// Builds a record with privacy-safe equivalence evidence derived from a
    /// unique, provider-returned qualified identity. Callers must not supply
    /// digests inferred from a model argument or digest suffix.
    pub fn new_with_canonical_target_digests(
        root_binding: String,
        stage: DecisionAnchorLineageStageV1,
        target_kind: DecisionAnchorTargetKindV1,
        result_target_kinds: impl IntoIterator<Item = DecisionAnchorTargetKindV1>,
        canonical_target_digests: impl IntoIterator<Item = String>,
    ) -> Option<Self> {
        let mut result_target_kinds = result_target_kinds.into_iter().collect::<Vec<_>>();
        result_target_kinds.sort();
        result_target_kinds.dedup();
        let mut canonical_target_digests = canonical_target_digests.into_iter().collect::<Vec<_>>();
        canonical_target_digests.sort();
        canonical_target_digests.dedup();
        (valid_root_binding(&root_binding)
            && result_target_kinds.len() <= MAX_DECISION_ANCHOR_RESULT_TARGET_KINDS
            && result_target_kinds
                .iter()
                .all(|kind| kind.is_result_target_kind())
            && (stage != DecisionAnchorLineageStageV1::Root || canonical_target_digests.is_empty())
            && canonical_target_digests.len() <= MAX_DECISION_ANCHOR_CANONICAL_TARGET_DIGESTS
            && canonical_target_digests
                .iter()
                .all(|digest| GraphCorrelationV1::is_valid_target_digest(digest)))
        .then_some(Self {
            version: DECISION_ANCHOR_LINEAGE_VERSION,
            root_binding,
            stage,
            target_kind,
            result_target_kinds,
            canonical_target_digests,
        })
    }

    /// Rejects unknown versions, malformed opaque bindings, duplicate or
    /// non-canonical type lists, and records that do not match V1 correlation.
    pub fn is_valid(&self) -> bool {
        self.version == DECISION_ANCHOR_LINEAGE_VERSION
            && valid_root_binding(&self.root_binding)
            && self.result_target_kinds.len() <= MAX_DECISION_ANCHOR_RESULT_TARGET_KINDS
            && self
                .result_target_kinds
                .iter()
                .all(|kind| kind.is_result_target_kind())
            && self
                .result_target_kinds
                .windows(2)
                .all(|pair| pair[0] < pair[1])
            && (self.stage != DecisionAnchorLineageStageV1::Root
                || self.canonical_target_digests.is_empty())
            && self.canonical_target_digests.len() <= MAX_DECISION_ANCHOR_CANONICAL_TARGET_DIGESTS
            && self
                .canonical_target_digests
                .iter()
                .all(|digest| GraphCorrelationV1::is_valid_target_digest(digest))
            && self
                .canonical_target_digests
                .windows(2)
                .all(|pair| pair[0] < pair[1])
    }

    /// Checks both the standalone contract and the existing closed V1 graph
    /// correlation carried beside it.
    pub fn is_valid_for(&self, correlation: &GraphCorrelationV1) -> bool {
        self.is_valid()
            && self.target_kind
                == DecisionAnchorTargetKindV1::from_graph_correlation(correlation.target_kind)
    }
}

fn valid_root_binding(value: &str) -> bool {
    value.len() == 36
        && value.as_bytes().get(14) == Some(&b'4')
        && matches!(value.as_bytes().get(19), Some(b'8' | b'9' | b'a' | b'b'))
        && value.bytes().enumerate().all(|(index, byte)| {
            matches!(index, 8 | 13 | 18 | 23) && byte == b'-'
                || !matches!(index, 8 | 13 | 18 | 23)
                    && byte.is_ascii_hexdigit()
                    && !byte.is_ascii_uppercase()
        })
}
